current/config/routes.rb
Rails.application.routes.draw do

  resources :candies_products

  resources :packings

  resources :candies

  resources :locations

  resources :products

  root 'home#index'

    get 'classic' => 'home#classic'
    get 'roshen' => 'home#roshen'
    get 'prestig' => 'home#prestig'
    get 'vip' => 'home#vip'
    get 'np' => 'home#np'
    get 'all' => 'home#all'
    get 'about_the_company' => 'home#about_the_company'
    get 'shares' => 'home#shares'
    get 'shipping_and_payment' => 'home#shipping_and_payment'
    get 'contacts' => 'home#contacts'

end

current/app/models/candy.rb
class Candy < ActiveRecord::Base

  has_attached_file :image, :styles => { :smal => "200x200>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  has_and_belongs_to_many :products

  # attr_accessible ...
  # has_many :candies_products
  # has_many :products, :through => :candies_products

  has_one :candies_product
end

current/app/controllers/candies_controller.rb
class CandiesController < ApplicationController
  before_action :set_candy, only: [:show, :edit, :update, :destroy]

  # GET /candies
  # GET /candies.json
  def index
    @candies = Candy.all
  end

  # GET /candies/1
  # GET /candies/1.json
  def show
  end

  # GET /candies/new
  def new
    @candy = Candy.new
  end

  # GET /candies/1/edit
  def edit
  end

  # POST /candies
  # POST /candies.json
  def create
    @candy = Candy.new(candy_params)

    respond_to do |format|
      if @candy.save
        format.html { redirect_to @candy, notice: 'Candy was successfully created.' }
        format.json { render :show, status: :created, location: @candy }
      else
        format.html { render :new }
        format.json { render json: @candy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /candies/1
  # PATCH/PUT /candies/1.json
  def update
    respond_to do |format|
      if @candy.update(candy_params)
        format.html { redirect_to @candy, notice: 'Candy was successfully updated.' }
        format.json { render :show, status: :ok, location: @candy }
      else
        format.html { render :edit }
        format.json { render json: @candy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candies/1
  # DELETE /candies/1.json
  def destroy
    @candy.destroy
    respond_to do |format|
      format.html { redirect_to candies_url, notice: 'Candy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_candy
      @candy = Candy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def candy_params
      params.require(:candy).permit(:title, :image, :manufacturer)
    end
end

current/app/helpers/candies_helper.rb
module CandiesHelper
end

current/app/views/candies/_form.html.erb
  <%= form_for(@candy) do |f| %>
    <% if @candy.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@candy.errors.count, "error") %> prohibited this candy from being saved:</h2>

        <ul>
        <% @candy.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>

      <div class="field">
      <%= f.file_field :image %>
    </div>


    <div class="field">
      <%= f.label :manufacturer %><br>
      <%= f.text_field :manufacturer %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

current/app/views/candies/edit.html.erb
<h1>Editing Candy</h1>

<%= render 'form' %>

<%= link_to 'Show', @candy %> |
<%= link_to 'Back', candies_path %>

current/app/views/candies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Candies</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Image</th>
      <th>Manufacturer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @candies.each do |candy| %>
      <tr>
        <td><%= candy.title %></td>
        <td><%= image_tag candy.image, :width => 50, :height => 50 %></td>
        <td><%= candy.manufacturer %></td>
        <td><%= link_to 'Show', candy %></td>
        <td><%= link_to 'Edit', edit_candy_path(candy) %></td>
        <td><%= link_to 'Destroy', candy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Candy', new_candy_path %>

current/app/views/candies/new.html.erb
<h1>New Candy</h1>

<%= render 'form' %>

<%= link_to 'Back', candies_path %>

current/app/views/candies/show.html.erb
<p id="notice"><%= notice %></p>



<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Title</th>
      <th>Manufacturer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><div id="img_for_show"><%= image_tag @candy.image, :width => 150, :height => 150 %></div></td>
        <td><%= @candy.title %></td>
        <td><%= @candy.manufacturer %></td>
      </tr>
  </tbody>
</table>

<p>
<%= link_to 'Edit', edit_candy_path(@candy) %> |
<%= link_to 'Back', candies_path %>
</p>