current/config/routes.rb
Rails.application.routes.draw do

  resources :candies_products

  resources :packings

  resources :candies

  resources :locations

  resources :products

  root 'home#index'

    get 'classic' => 'home#classic'
    get 'roshen' => 'home#roshen'
    get 'prestig' => 'home#prestig'
    get 'vip' => 'home#vip'
    get 'np' => 'home#np'
    get 'all' => 'home#all'
    get 'about_the_company' => 'home#about_the_company'
    get 'shares' => 'home#shares'
    get 'shipping_and_payment' => 'home#shipping_and_payment'
    get 'contacts' => 'home#contacts'

end

current/app/models/candies_product.rb
class CandiesProduct < ActiveRecord::Base
	  belongs_to :candy
      belongs_to :products
end

current/app/controllers/candies_products_controller.rb
class CandiesProductsController < ApplicationController
  before_action :set_candies_product, only: [:show, :edit, :update, :destroy]

  # GET /candies_products
  # GET /candies_products.json
  def index
    @candies_products = CandiesProduct.all
  end

  # GET /candies_products/1
  # GET /candies_products/1.json
  def show
  end

  # GET /candies_products/new
  def new
    @candies_product = CandiesProduct.new
  end

  # GET /candies_products/1/edit
  def edit
  end

  # POST /candies_products
  # POST /candies_products.json
  def create
    @candies_product = CandiesProduct.new(candies_product_params)

    respond_to do |format|
      if @candies_product.save
        format.html { redirect_to @candies_product, notice: 'Candies product was successfully created.' }
        format.json { render :show, status: :created, location: @candies_product }
      else
        format.html { render :new }
        format.json { render json: @candies_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /candies_products/1
  # PATCH/PUT /candies_products/1.json
  def update
    respond_to do |format|
      if @candies_product.update(candies_product_params)
        format.html { redirect_to @candies_product, notice: 'Candies product was successfully updated.' }
        format.json { render :show, status: :ok, location: @candies_product }
      else
        format.html { render :edit }
        format.json { render json: @candies_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candies_products/1
  # DELETE /candies_products/1.json
  def destroy
    @candies_product.destroy
    respond_to do |format|
      format.html { redirect_to candies_products_url, notice: 'Candies product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_candies_product
      @candies_product = CandiesProduct.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def candies_product_params
      params.require(:candies_product).permit(:product_id, :candy_id, :count, :id)
    end
end

current/app/helpers/candies_products_helper.rb
module CandiesProductsHelper
end

current/app/views/candies_products/_form.html.erb
<%= form_for(@candies_product) do |f| %>
  <% if @candies_product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@candies_product.errors.count, "error") %> prohibited this candies_product from being saved:</h2>

      <ul>
      <% @candies_product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :candy_id %><br>
    <%= f.number_field :candy_id %>
  </div>
  <div class="field">
    <%= f.label :count %><br>
    <%= f.number_field :count %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

current/app/views/candies_products/edit.html.erb
<h1>Editing Candies Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @candies_product %> |
<%= link_to 'Back', :back  %>

current/app/views/candies_products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Candies Products</h1>

<table>
  <thead>
    <tr>
          <th>ID</th>
      <th>Product</th>
      <th>Candy</th>
      <th>Count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @candies_products.each do |candies_product| %>
      <tr>
              <td><%= candies_product.id %></td>
        <td><%= candies_product.product_id %></td>
        <td><%= candies_product.candy_id %></td>
        <td><%= candies_product.count %></td>
        <td><%= link_to 'Show', candies_product %></td>
        <td><%= link_to 'Edit', edit_candies_product_path(candies_product) %></td>
        <td><%= link_to 'Destroy', candies_product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Candies product', new_candies_product_path %>

current/app/views/candies_products/new.html.erb
<h1>New Candies Product</h1>

<%= render 'form' %>

<%= link_to 'Back', candies_products_path %>

current/app/views/candies_products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @candies_product.product_id %>
</p>

<p>
  <strong>Candy:</strong>
  <%= @candies_product.candy_id %>
</p>

<p>
  <strong>Count:</strong>
  <%= @candies_product.count %>
</p>

<%= link_to 'Edit', edit_candies_product_path(@candies_product) %> |
<%= link_to 'Back', candies_products_path %>